### PR TITLE
Add progress bars to the simulation cards

### PR DESCRIPTION
**Pull request by jbeezley**
@jtomeck This is my attempt at progress bars.  The API isn't quite complete, but eventually I will be able to do live updates for non-indeterminate progress.  There will also be a failure state, which I was planning on just making a red bar.  Let me know if you have any ideas to make this look better.

There will also be a need (probably) to show a similar progress bar in the simulation viewer component (https://github.com/NutritionalLungImmunity/lung-fungal-web/blob/master/src/components/SimulationViewer.vue), but that page probably requires a more thorough  redesign anyway.  I might start by just copying the status bar from the cards and make it float somewhere over the simulation.

### CODE REVIEW

**Comment by jtomeck** [comment]
@jbeezley - The progress bars look really good. I created an alert for if there's a simulation error. It'll need to be hooked up to when there's an actual error, but I wanted to throw the component in there.

My thought is that the user could click learn more to go somewhere to troubleshoot? Not sure what the workflow should be, but the idea's there. Let me know if you need anything else.

**Comment by jtomeck** [comment]
I'm also struggling to figure out how to remove the white background from the simulation list. It appears to be the `.theme--light` class on the `.v-tabs-items` element, but I can't tell how that class is getting added.

**Comment by jbeezley** [comment]
Yeah, I don't know where that class is coming from either.

**Comment by jbeezley** [comment]
https://github.com/vuetifyjs/vuetify/issues/10283 I'll add some css to make it transparent.

**Comment by jtomeck** [comment]
> [vuetifyjs/vuetify#10283](https://github.com/vuetifyjs/vuetify/issues/10283) I'll add some css to make it transparent.

Should be all set with my last commit

**Comment by jbeezley** [comment]
And... you beat me to it.

**Pull request merged**
